### PR TITLE
Fixed an issue with a multi-threaded environment.

### PR DESCRIPTION
**Pull request by dbelouslv**
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)    at MySql.Data.MySqlClient.MySqlPoolManager.GetPoolAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)    at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)    at MySql.Data.MySqlClient.MySqlConnection.Open().

Use Concurrent Collections: In a multi-threaded environment, it's best to use concurrent collections that are designed to be thread-safe. In .NET, you have access to collections like ConcurrentDictionary and ConcurrentQueue which are designed for concurrent access.

Replace your regular Dictionary with a ConcurrentDictionary. This should help prevent concurrent update issues.

### CODE REVIEW

**Comment by dbelouslv** [comment]
@mysql-oca-bot - "You successfully signed an OCA. As a next step, Oracle will review your OCA submission."

**Comment by bgrainger** [comment]
This crash was already fixed here: https://github.com/mysql/mysql-connector-net/pull/56.

**Comment by nick-asher** [comment]
As of MySql.Data version 8.1.0 via a dependency on MySql.EntityFrameworkCore, the crash has not been fixed. Swapping to a ConcurrentDictionary seems like a sensible change?

**Comment by dbelouslv** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
