### PR TITLE
Fix generating sql literal for byte array.

### PR DESCRIPTION
**Pull request by NaNgets**
Fix generating sql literal for byte array.

Related bug: https://bugs.mysql.com/bug.php?id=93398

### CODE REVIEW

**Comment by NaNgets** [comment]
Hi,
I don't want to sign the OCA, you can feel free to copy\rewrite the PR to your needs.

**Comment by mysql-admin** [comment]
@NaNgets : Thanks for your suggestion
==Omer

**Comment by kbokdia** [comment]
Hey, Any updates on this even I am facing the issue while using contains. I am currently using MySql.Data.EntityFrameworkCore 8.0.21

**Comment by GDreyV** [comment]
Hi, still nothing? Please just rewrite the PR and apply it

**Comment by juandpaez** [comment]
Hi, I am still having the same exact issue as described here. I am using nuget package MySql.EntityFrameworkCore 5.0.5+MySQL8.0.26 published: Tuesday, July 20, 2021.
Any information would be very appreciated.
Thanks

**Comment by mysql-admin** [comment]
Please use https://forums.mysql.com/ for questions/inquiries/discussions
or for specific issues related to a bug - the bug record on bugs.mysql.com
Thanks
==Omer

**Comment by ugumba** [comment]
This is still an issue on EF Core 6.0 with MySQL.Data 8.0.28.  Given the BINARY(32) column Operations.Hash and
```
IEnumerable<byte[]> hashes;
```
then both
```
source.Where(o => hashes.Any(h => o.Hash == h))
```
and
```
source.Where(o => hashes.Contains(o.Hash))
```
are both injecting the literal string "System.Byte[]" into the generated SQL:
```
SELECT `o`.`Hash`, `o`.`Id`
FROM `Operations` AS `o`
WHERE `o`.`Hash` = System.Byte[]
```
causing
```
MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[]' at line 3
```
Also reported [here](https://bugs.mysql.com/106900).

**Pull request closed without merging**
