### PR TITLE
Fixing encoding for entity framework core

### PR DESCRIPTION
**Pull request by kleberksms**
this is a same correction on https://github.com/SapientGuardian/mysql-connector-net-netstandard/pull/32

### CODE REVIEW

**Comment by kleberksms** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by danielterabyte** [comment]
Any news about the acceptance of this pull request?

I am facing this problem right now consuming a mantis database in a .net core app.

**Comment by kleberksms** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by kleberksms** [comment]
@mysql-oca-bot,  I asked to Miguel about release cycle and when merge my commit, in
https://github.com/mysql/mysql-connector-net/pull/16/commits/a87b165b0f629395a50d0e8712199104d9c3a98e I read about time for a new release cycle, this feature will be integrated  only july?

**Pull request closed without merging**
